### ISSUE TITLE
Swift-Package Version Number

### ISSUE THREAD

**Issue by omrd** [robb/HTML-DSL#9]
I am trying to import this package into my project, but keep getting the same error. 

> because no versions of HTML-DSL match the requirement 0.0.1..<1.0.0 and root depends on HTML-DSL 0.0.1..<1.0.0, version solving failed`

It doesn't matter what version I set it to, it's still the same issue. 

Thanks

**Comment by robb** [comment]
[Here's how I'm using it in my website](https://github.com/robb/robb.swift/blob/a4c12a1e4ea2bf3cae30e73f5349d31569127949/Package.swift#L19) by working directly against the `master` branch. That said, I'd _strongly_ recommend you fork this repository and use your own fork as I am making breaking changes or rewrite the git history arbitrarily.
